version: '3.9'

services:
  web:
    image: ${WEB_ECR_REPO_URI}:${USER}
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
  web_prod:
    image: ${WEB_PROD_ECR_REPO_URI}:${USER}
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
